version: '3.3'
services:
    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - mysql:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - '3307:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        expose:
            - 80
        ports:
            - 8085:80
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql

volumes:
    mysql:
